version: "3.8"
services:
  celery-1:
    image: celery
    container_name: celery-1
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ailyze-database.postgres.database.azure.com
      DB_USER: ailyzeadmin
      DB_PASSWORD: Database@124
      DB_NAME: stage
      CELERY_BROKER_URL: "amqp://staginguser:stagingpassword@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: celery  -A AILYZE worker -l info --autoscale=10,4 -Q themeandresearchquestion -n theme -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    networks:
      ailyze-nw:

  celery-2:
    image: celery
    container_name: celery-2
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ailyze-database.postgres.database.azure.com
      DB_USER: ailyzeadmin
      DB_PASSWORD: Database@124
      DB_NAME: stage
      CELERY_BROKER_URL: "amqp://staginguser:stagingpassword@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: celery -A AILYZE worker -l info --autoscale=10,4 -Q frequency_analysis -n frequency -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    networks:
      ailyze-nw:

  celery-3:
    image: celery
    container_name: celery-3
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ailyze-database.postgres.database.azure.com
      DB_USER: ailyzeadmin
      DB_PASSWORD: Database@124
      DB_NAME: stage
      CELERY_BROKER_URL: "amqp://staginguser:stagingpassword@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: celery -A AILYZE worker -l info --autoscale=10,4 -Q compareviewpoint -n compare -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    networks:
      ailyze-nw:
      

  celery-4:
    image: celery
    container_name: celery-4
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ailyze-database.postgres.database.azure.com
      DB_USER: ailyzeadmin
      DB_PASSWORD: Database@124
      DB_NAME: stage
      CELERY_BROKER_URL: "amqp://staginguser:stagingpassword@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: celery -A AILYZE worker -l info --autoscale=10,4 -Q prepare_bot -n chatbot -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-chatbot
    networks:
      ailyze-nw:
