version: "3.8"
services:
  backend-oneclickinsight:
    container_name: backend-oneclickinsight
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
    ports:
      - "8001:8001"
    environment:
      DB_HOST: ailyze-database.postgres.database.azure.com
      DB_NAME: stage
      DB_USER: ailyzeadmin
      DB_PASSWORD: Database@124
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      CELERY_BROKER_URL: "amqp://staginguser:stagingpassword@rabbitmq:5672//"
    networks:
      ailyze-nw:
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: sh -c "ls AILYZE && gunicorn --bind 0.0.0.0:8001 AILYZE.asgi -w 4 -k uvicorn.workers.UvicornWorker --log-level info --access-logfile ./access.log  --error-logfile ./error.log"

